# Generated by Django 5.2.7 on 2025-10-19 15:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('books', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, null=True, unique=True)),
                ('contact_no', models.CharField(max_length=11, null=True, unique=True)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=20, null=True)),
                ('deposit_date', models.DateField(auto_now_add=True, null=True)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=12, null=True)),
                ('dob', models.DateField(null=True)),
                ('joining_time', models.DateTimeField(auto_now=True, null=True)),
                ('user_image', models.ImageField(blank=True, null=True, upload_to='user_image')),
                ('user_type', models.CharField(choices=[('ADMINISTRATOR', 'ADMINISTRATOR'), ('USER', 'USER'), ('SUPER_USER', 'SUPER_USER')], null=True)),
                ('borrowed_books', models.ManyToManyField(blank=True, related_name='borrowed_books', to='books.book')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_acc', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
