# Generated by Django 5.2.7 on 2025-10-19 17:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField(null=True)),
                ('author', models.CharField(max_length=150, null=True)),
                ('add_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('borrow_price', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('book_image', models.ImageField(null=True, upload_to='book_image')),
                ('quantity', models.IntegerField(null=True)),
                ('total_borrowed_time', models.IntegerField(default=0, null=True)),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_add', to=settings.AUTH_USER_MODEL)),
                ('category', models.ManyToManyField(related_name='book_categories', to='categories.category')),
            ],
        ),
    ]
